spring:
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?autoReconnect=true&useSSL=false
    username: postgres
    #password: ENC(2L3MvBFx+sCd0DQ79sMY6wR0bJvSGq3R)
    password: New1234!
    
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true
    
    
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: gigageniefortune
    

server:
  port: 8080
  context-path: /
  jsp-servlet:
    init-parameters: 
      developement: true
      

